### ISSUE TITLE
User module alwas shows on filament user roles

### ISSUE THREAD

**Issue by arpaulustindi** [3x1io/filament-user#14]
Alwas show user model when roles has filament user

**Comment by ShaungBhone** [comment]
What's that?
@arpaulustindi

**Comment by temandroid** [comment]
What he means is that the "Users" section is visible without an access role, but shouldn't

**Comment by temandroid** [comment]
> Alwas show user model when roles has filament user

Try php artisan shield:generate --all

**Comment by fadymondy** [comment]
you can use the new version support filamentv3

https://www.github.com/tomatophp/filament-users

**Comment by sourcecodeit** [comment]
> > Alwas show user model when roles has filament user
> 
> Try php artisan shield:generate --all

I use Filament 3 and I had to run this command too, otherwise my users were seeing the Users management even if their role didn't permit.
