### ISSUE TITLE
Impersonate button doesn't show

### ISSUE THREAD

**Issue by abdullafahem** [3x1io/filament-user#15]
![image](https://user-images.githubusercontent.com/49653818/224535043-6079204b-4b0a-4b6e-8d73-279aa62ebb01.png)

**Comment by abdullafahem** [comment]
I have the older version of the library work well.
I tried this new version of my new app doesn't show the button any solution, please?

**Comment by socbaysky** [comment]
find config/filament-user.php -> add "impersonate" => true,
