### ISSUE TITLE
Support filament-shield V2

### ISSUE THREAD

**Issue by MarJose123** [3x1io/filament-user#8]
Please support filament-shield V2

![image](https://user-images.githubusercontent.com/18107626/179658773-8903e4d0-8dbc-4790-9d0d-e6a1ce1e6209.png)

**Comment by yinsystems** [comment]
Just had the same issue installing  it

**Comment by mnafullstack** [comment]
Same issue here. Is admin available to review this issue?

**Comment by pschilly** [comment]
I suspect it is an issue of the composer requirements moreso than anything else.

**Comment by vijayrana99** [comment]
I am also facing the same issue. My shield version is 2.0 and I am unable to install this package.

**Comment by MKWebDesign** [comment]
facing the same issue here on a fresh filament install 
![image](https://user-images.githubusercontent.com/1301187/181748587-5a6e3e97-1841-4c07-bee0-f906ff775e57.png)

**Comment by yinsystems** [comment]
Try `composer update` and `composer fund`
